### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by Tomingz** [shipubupt/NIPS2018#5]
ubuntu16.04 ++940mx(2gb)+cuda8.0+py27+pytorch0.3.0post4 .I have changed batch_test=1 in option.py .but it is always out of memory,how to solve it?

**Comment by SMZCC** [comment]
You can change a computer 😅 2gb GPU is too small

**Comment by Tomingz** [comment]
@SMZCC  I think too

**Comment by Tomingz** [comment]
I have solved this problem by changing the batch in option.py
